language: node_js

node_js:
  - 8
  - 12

install:
  - npm install -g codecov
  - npm install

script:
  - npm test

after_success:
  - codecov

before_deploy:
  - npm config set @vbs:registry https://registry.npmjs.com
  - npm run build
  - cp -r build dist
  - cp README.md ./dist/
  - cp package*.json ./dist/
  - cd dist

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    tags: true
